# Generated by Django 6.0.1 on 2026-02-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='parsed_text',
            field=models.TextField(blank=True, help_text='AI Extracted text from resume'),
        ),
    ]
